# CAMERA_SETUP
CAMERA_INDEX = 0

FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FPS = 15

# Motion Detection
MOTION_THRESHOLD = 5000
BLUR_SIZE = (21, 21)
MIN_DELTA = 25

SNAPSHOT_DIR = "snapshots"
SNAPSHOT_COOLDOWN = 10

# AI Configuration
AI_MODEL_DIR = "models"
AI_CONFIDENCE = 0.6
AI_FRAME_SKIP = 3